// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/ping": {
            "get": {
                "description": "see if the server is up and running with this health check endpoint",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "healthcheck"
                ],
                "summary": "Check API health",
                "responses": {
                    "200": {
                        "description": "{\\\"ping\\\": \\\"pong\\\"}",
                        "schema": {
                            "$ref": "#/definitions/main.PingPong"
                        }
                    }
                }
            }
        },
        "/question": {
            "get": {
                "description": "Retrieves all of the questions from the database given input query parameters.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "question"
                ],
                "summary": "Get zero or more questions",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Limit",
                        "name": "limit",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Final ID from previous page",
                        "name": "finalId",
                        "in": "query"
                    },
                    {
                        "type": "array",
                        "items": {
                            "type": "string"
                        },
                        "collectionFormat": "csv",
                        "description": "Tag to match (specify multiple times for \u0026\u0026 match)",
                        "name": "tag",
                        "in": "query"
                    },
                    {
                        "type": "boolean",
                        "description": "Get a random question",
                        "name": "random",
                        "in": "query"
                    }
                ],
                "responses": {
                    "201": {
                        "description": "The questions that were found (or weren't)",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/application.Question"
                            }
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/responses.ErrorResponse"
                        }
                    }
                }
            },
            "post": {
                "description": "Will create a brand new question in the database.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "question"
                ],
                "summary": "Create a question",
                "parameters": [
                    {
                        "description": "Question data",
                        "name": "question",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/application.NewQuestion"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/application.Question"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/responses.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/responses.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/question/{questionId}": {
            "get": {
                "description": "will get one question using its unique id.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "question"
                ],
                "summary": "Get one question.",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Question ID",
                        "name": "questionId",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/application.Question"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/responses.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/responses.ErrorResponse"
                        }
                    }
                }
            },
            "put": {
                "description": "Update an existing question in the database. If the question does not exist it will be created.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "question"
                ],
                "summary": "Update a question given its ID",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Question ID",
                        "name": "questionId",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Question data",
                        "name": "question",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/application.NewQuestion"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "The created question",
                        "schema": {
                            "$ref": "#/definitions/application.Question"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/responses.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/responses.ErrorResponse"
                        }
                    }
                }
            },
            "delete": {
                "description": "Deletes one question using its id. If the question already does not exist, this will return successfully.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "question"
                ],
                "summary": "Delete one question.",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Question ID",
                        "name": "questionId",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/responses.SuccessResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/responses.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/user": {
            "post": {
                "description": "Creates a new user in the database and returns that new user",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "user"
                ],
                "summary": "Create a user",
                "parameters": [
                    {
                        "description": "User data",
                        "name": "user",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/requests.PostUserRequest"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/application.User"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/responses.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/responses.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/user/{userId}": {
            "get": {
                "description": "Given the user id, grab the user from the database",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "user"
                ],
                "summary": "Get a user given their ID",
                "parameters": [
                    {
                        "type": "string",
                        "description": "User ID",
                        "name": "userId",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/application.User"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/responses.ErrorResponse"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/responses.ErrorResponse"
                        }
                    }
                }
            },
            "put": {
                "description": "Updates the user given the user id and the update data",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "user"
                ],
                "summary": "Update a user given their ID",
                "parameters": [
                    {
                        "type": "string",
                        "description": "User ID",
                        "name": "userId",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "User data",
                        "name": "user",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/user.BaseUser"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK"
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/responses.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/responses.ErrorResponse"
                        }
                    }
                }
            },
            "delete": {
                "description": "Delete a user from the database given their user id",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "user"
                ],
                "summary": "Delete a user given their ID",
                "parameters": [
                    {
                        "type": "string",
                        "description": "User ID",
                        "name": "userId",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/responses.DeleteUserResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/responses.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/responses.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/user/{userId}/list": {
            "get": {
                "description": "Get all of the lists for a user.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "list"
                ],
                "summary": "Get lists",
                "parameters": [
                    {
                        "type": "string",
                        "description": "User ID",
                        "name": "userId",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/list.List"
                            }
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/responses.ErrorResponse"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/responses.ErrorResponse"
                        }
                    }
                }
            },
            "post": {
                "description": "Create a list",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "list"
                ],
                "summary": "Create a list",
                "parameters": [
                    {
                        "type": "string",
                        "description": "User ID",
                        "name": "userId",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "List data",
                        "name": "list",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/requests.PostUserListRequest"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/list.List"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/responses.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/responses.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/user/{userId}/list/{listId}": {
            "get": {
                "description": "Get a list and its questions from a given user list.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "list question"
                ],
                "summary": "Get a list",
                "parameters": [
                    {
                        "type": "string",
                        "description": "User ID",
                        "name": "userId",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "List ID",
                        "name": "listId",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "description": "Limit",
                        "name": "limit",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Final ID from previous page",
                        "name": "finalId",
                        "in": "query"
                    },
                    {
                        "type": "array",
                        "items": {
                            "type": "string"
                        },
                        "collectionFormat": "csv",
                        "description": "Tag to match (specify multiple times for \u0026\u0026 match)",
                        "name": "tag",
                        "in": "query"
                    },
                    {
                        "type": "boolean",
                        "description": "Get a random question",
                        "name": "random",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/responses.GetUserListByIdResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/responses.ErrorResponse"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/responses.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/responses.ErrorResponse"
                        }
                    }
                }
            },
            "put": {
                "description": "Update a list",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "list"
                ],
                "summary": "Update a list",
                "parameters": [
                    {
                        "type": "string",
                        "description": "User ID",
                        "name": "userId",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "List ID",
                        "name": "listId",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "List data",
                        "name": "list",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/requests.PutUserListRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/responses.SuccessResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/responses.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/responses.ErrorResponse"
                        }
                    }
                }
            },
            "delete": {
                "description": "Deletes the list from the user profile and removes all questions from the list. If the list does not exist, returns successfully.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "list"
                ],
                "summary": "Delete a list",
                "parameters": [
                    {
                        "type": "string",
                        "description": "User ID",
                        "name": "userId",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "List ID",
                        "name": "listId",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK"
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/responses.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/responses.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/user/{userId}/list/{listId}/question/{questionId}": {
            "get": {
                "description": "Get a question from a list",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "list question"
                ],
                "summary": "Get a question from a list",
                "parameters": [
                    {
                        "type": "string",
                        "description": "User ID",
                        "name": "userId",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "List ID",
                        "name": "listId",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Question ID",
                        "name": "questionId",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/application.Question"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/responses.ErrorResponse"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/responses.ErrorResponse"
                        }
                    }
                }
            },
            "post": {
                "description": "Add a question to a list",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "list question"
                ],
                "summary": "Add a question to a list",
                "parameters": [
                    {
                        "type": "string",
                        "description": "User ID",
                        "name": "userId",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "List ID",
                        "name": "listId",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Question ID",
                        "name": "questionId",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/responses.SuccessResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/responses.ErrorResponse"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/responses.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/responses.ErrorResponse"
                        }
                    }
                }
            },
            "delete": {
                "description": "Delete a question from a list. If the question does not exist in the list, returns successfully.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "list question"
                ],
                "summary": "Delete a question from a list",
                "parameters": [
                    {
                        "type": "string",
                        "description": "User ID",
                        "name": "userId",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "List ID",
                        "name": "listId",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Question ID",
                        "name": "questionId",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/responses.SuccessResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/responses.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/responses.ErrorResponse"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "application.NewQuestion": {
            "type": "object",
            "required": [
                "prompt",
                "tags"
            ],
            "properties": {
                "prompt": {
                    "description": "The actual question itself.",
                    "type": "string"
                },
                "tags": {
                    "description": "The tags identifying what kind of question this is.",
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                }
            }
        },
        "application.Question": {
            "type": "object",
            "required": [
                "prompt",
                "questionId",
                "tags"
            ],
            "properties": {
                "prompt": {
                    "description": "The actual question itself.",
                    "type": "string"
                },
                "questionId": {
                    "description": "The database identifier for this question.",
                    "type": "string"
                },
                "tags": {
                    "description": "The tags identifying what kind of question this is.",
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                }
            }
        },
        "application.User": {
            "type": "object",
            "required": [
                "email",
                "firebaseId",
                "lists",
                "settings",
                "subscription",
                "tier",
                "userId"
            ],
            "properties": {
                "email": {
                    "description": "The user's username.",
                    "type": "string"
                },
                "firebaseId": {
                    "description": "The unique user identifier from firebase.",
                    "type": "string"
                },
                "lists": {
                    "description": "The list of question lists that the user has created.",
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/list.List"
                    }
                },
                "name": {
                    "description": "The user's username.",
                    "type": "string"
                },
                "settings": {
                    "description": "The users settings and preferences.",
                    "allOf": [
                        {
                            "$ref": "#/definitions/user.UserSettings"
                        }
                    ]
                },
                "subscription": {
                    "description": "The user's subscription information.",
                    "allOf": [
                        {
                            "$ref": "#/definitions/user.UserSubscription"
                        }
                    ]
                },
                "tier": {
                    "description": "The user's subscription tier. One of \"free\" | \"lite\" | \"premium\"",
                    "type": "string"
                },
                "userId": {
                    "description": "The unique identifier for the user.",
                    "type": "string"
                }
            }
        },
        "list.List": {
            "type": "object",
            "required": [
                "listId",
                "name"
            ],
            "properties": {
                "listId": {
                    "description": "The unique identifier for the list.",
                    "type": "string"
                },
                "name": {
                    "description": "The human readable name for the list",
                    "type": "string"
                }
            }
        },
        "main.PingPong": {
            "type": "object",
            "properties": {
                "ping": {
                    "type": "string"
                }
            }
        },
        "requests.PostUserListRequest": {
            "type": "object",
            "required": [
                "name"
            ],
            "properties": {
                "name": {
                    "description": "The name of the new list",
                    "type": "string"
                }
            }
        },
        "requests.PostUserRequest": {
            "type": "object",
            "required": [
                "email",
                "firebaseId",
                "settings",
                "subscription",
                "tier"
            ],
            "properties": {
                "email": {
                    "description": "The user's username.",
                    "type": "string"
                },
                "firebaseId": {
                    "description": "The unique user identifier from firebase.",
                    "type": "string"
                },
                "lists": {
                    "description": "The list of question lists that the user has created.",
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/list.List"
                    }
                },
                "name": {
                    "description": "The user's username.",
                    "type": "string"
                },
                "settings": {
                    "description": "The users settings and preferences.",
                    "allOf": [
                        {
                            "$ref": "#/definitions/user.UserSettings"
                        }
                    ]
                },
                "subscription": {
                    "description": "The user's subscription information.",
                    "allOf": [
                        {
                            "$ref": "#/definitions/user.UserSubscription"
                        }
                    ]
                },
                "tier": {
                    "description": "The user's subscription tier. One of \"free\" | \"lite\" | \"premium\"",
                    "type": "string"
                }
            }
        },
        "requests.PutUserListRequest": {
            "type": "object",
            "required": [
                "name"
            ],
            "properties": {
                "name": {
                    "description": "The name for the list.",
                    "type": "string"
                }
            }
        },
        "responses.DeleteUserResponse": {
            "type": "object",
            "properties": {
                "deleteTime": {
                    "type": "integer"
                },
                "success": {
                    "type": "boolean"
                }
            }
        },
        "responses.ErrorResponse": {
            "type": "object",
            "required": [
                "error"
            ],
            "properties": {
                "error": {
                    "description": "The text of the error itself",
                    "type": "string"
                }
            }
        },
        "responses.GetUserListByIdResponse": {
            "type": "object",
            "properties": {
                "list": {
                    "$ref": "#/definitions/list.List"
                },
                "questions": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/application.Question"
                    }
                }
            }
        },
        "responses.SuccessResponse": {
            "type": "object",
            "properties": {
                "success": {
                    "description": "This response means that the whole operation was successful, but this\ncan be false if for example the delete request attempted to delete\nsomething that does not exist. It is \"successful\" in the sense\nthat the object intended for deletion does not exist after the request,\nand unsuccessful in that the request played no part in the deletion.",
                    "type": "boolean"
                },
                "time": {
                    "description": "The approximate time on the server when the operation was completed.",
                    "type": "integer"
                }
            }
        },
        "user.BaseUser": {
            "type": "object",
            "required": [
                "email",
                "firebaseId",
                "lists",
                "settings",
                "subscription",
                "tier"
            ],
            "properties": {
                "email": {
                    "description": "The user's username.",
                    "type": "string"
                },
                "firebaseId": {
                    "description": "The unique user identifier from firebase.",
                    "type": "string"
                },
                "lists": {
                    "description": "The list of question lists that the user has created.",
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/list.List"
                    }
                },
                "name": {
                    "description": "The user's username.",
                    "type": "string"
                },
                "settings": {
                    "description": "The users settings and preferences.",
                    "allOf": [
                        {
                            "$ref": "#/definitions/user.UserSettings"
                        }
                    ]
                },
                "subscription": {
                    "description": "The user's subscription information.",
                    "allOf": [
                        {
                            "$ref": "#/definitions/user.UserSubscription"
                        }
                    ]
                },
                "tier": {
                    "description": "The user's subscription tier. One of \"free\" | \"lite\" | \"premium\"",
                    "type": "string"
                }
            }
        },
        "user.UserColorScheme": {
            "type": "object",
            "required": [
                "background",
                "foreground",
                "highlightedBackground",
                "highlightedForeground"
            ],
            "properties": {
                "background": {
                    "description": "The hex code for the color to use in the background OR the word \"default\"\nto use the default setting on the user's device.",
                    "type": "string"
                },
                "foreground": {
                    "description": "The hex code for the color to use in the foreground OR the word \"default\"\nto use the default setting on the user's device.",
                    "type": "string"
                },
                "highlightedBackground": {
                    "description": "The hex code for the color to use in the highlighted background OR the\nword \"default\" to use the default setting on the user's device.",
                    "type": "string"
                },
                "highlightedForeground": {
                    "description": "The hex code for the color to use in the highlighted background OR the\nword \"default\" to use the default setting on the user's device.",
                    "type": "string"
                }
            }
        },
        "user.UserSettings": {
            "type": "object",
            "required": [
                "colorScheme"
            ],
            "properties": {
                "colorScheme": {
                    "description": "The color scheme that the user has chose.",
                    "allOf": [
                        {
                            "$ref": "#/definitions/user.UserColorScheme"
                        }
                    ]
                }
            }
        },
        "user.UserSubscription": {
            "type": "object",
            "required": [
                "renewalDate"
            ],
            "properties": {
                "payCadence": {
                    "description": "How often a user makes payments for their subscription.\nCurrently \"monthly\" is the only supported value.",
                    "type": "string"
                },
                "renewalDate": {
                    "description": "When the next payment is to be made to renew the subscription.",
                    "type": "string"
                }
            }
        }
    },
    "securityDefinitions": {
        "token": {
            "description": "Type \"Bearer\" followed by a space and JWT token.",
            "type": "apiKey",
            "name": "Authorization",
            "in": "header"
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "v1",
	Host:             "",
	BasePath:         "/",
	Schemes:          []string{},
	Title:            "Ask Me Anything API",
	Description:      "",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
